BEGIN TRANSACTION;
CREATE TABLE Addresses (user VARCHAR (30) PRIMARY KEY UNIQUE ON CONFLICT REPLACE NOT NULL, address VARCHAR (160) NOT NULL);
CREATE TABLE GiftAssignment (gifter VARCHAR (30) REFERENCES Addresses (user) UNIQUE NOT NULL, gifted VARCHAR (30) REFERENCES Addresses (user) UNIQUE NOT NULL);
CREATE TABLE SentConfirmations (user VARCHAR (30) REFERENCES Addresses (user) NOT NULL UNIQUE, datetime DATETIME NOT NULL);
CREATE TABLE ReceivedConfirmations (user VARCHAR (30) REFERENCES Addresses (user) NOT NULL UNIQUE, datetime DATETIME NOT NULL);
COMMIT;
