help_text = "Jestem botem o bardzo małym rozumku i nie rozumiem :(. Pomoc na: [jeszcze nie ma, bo to tylko testy]"
data_saved = "Zapisałem poprawnie Twoje dane. Cierpliwie czekaj na losowanie."
data_deleted = "Usunąłem Twoje dane z listy uczestników."
error_text = "Oj, coś poszło nie tak. :("
public_message_warn = "Usuń czym prędzej ostatnią wiadomość do mnie i wyślij ją jeszcze raz. Tym razem prywatnie. (>> a nie >)"
gift_assigment_notification = "Wylosowałem Ci: ^{}. Ślij prezent na adres: {}"
sent_confirmation_saved = "Zapisałem potwierdzenie wysłania."
received_confirmation_saved = "Zapisałem potwierdzenie odebrania przesyłki. Dzięki za udział w zabawie i miłej lektury. :)"
confirmation_already_exists = "Mam już potwierdzenie w bazie. Nie zapisuję go drugi raz."
data_gathering_disabled = "Niestety, trochę za późno. Lista uczestników została zamknięta."
not_a_participant = "Kim jesteś? Nie mam Cię na liście uczestników."
package_sent_notification = "Twój prezent został wysłany."
package_received_notificaton = "Prezent od Ciebie został odebrany."
